# Generated by Django 4.2.30 on 2026-07-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField(help_text='Calories per serving')),
                ('protein', models.FloatField(default=0.0, help_text='Protein in grams per serving')),
                ('carbs', models.FloatField(default=0.0, help_text='Carbohydrates in grams per serving')),
                ('fat', models.FloatField(default=0.0, help_text='Fat in grams per serving')),
                ('serving_size', models.CharField(default='100g', help_text='e.g. 100g, 1 serving, 1 piece', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.FloatField(default=1.0, help_text='Multiplier of serving size')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='diet.meal')),
            ],
        ),
    ]
